//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_PCL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            //this.Deliveries = new HashSet<Delivery>();
        }
    
        public int Id { get; set; }
        public string Details { get; set; }
        public bool Delivered { get; set; }
        public bool Status { get; set; }
        public string UserId { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool Canceled { get; set; }
        public Nullable<int> PersonProduct_Id { get; set; }
    
        //public virtual AspNetUser AspNetUser { get; set; }
        //public virtual PersonProduct PersonProduct { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}
