//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_WebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class PersonProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonProduct()
        {
            //this.Appointments = new HashSet<Appointment>();
            //this.Deliveries = new HashSet<Delivery>();
            //this.PersonProductMarks = new HashSet<PersonProductMark>();
            //this.ReservedProducts = new HashSet<ReservedProduct>();
        }

        [JsonProperty("Id")]
        public int Id { get; set; }

        [JsonProperty("UserId")]
        public string UserId { get; set; }

        [JsonProperty("ProductId")]
        public int ProductId { get; set; }

        [JsonProperty("HarvestDate")]
        public DateTime HarvestDate { get; set; }

        [JsonProperty("Neto")]
        public string Neto { get; set; }

        [JsonProperty("Bruto")]
        public string Bruto { get; set; }

        [JsonProperty("ExparationDate")]
        public System.DateTime ExparationDate { get; set; }

        [JsonProperty("Quality")]
        public string Quality { get; set; }

        [JsonProperty("FieldId")]
        public int FieldId { get; set; }

        [JsonProperty("Damaged")]
        public bool Damaged { get; set; }

        [JsonProperty("CircaValue")]
        public decimal CircaValue { get; set; }

        [JsonProperty("Urgently")]
        public bool Urgently { get; set; }

        [JsonProperty("Status")]
        public bool Status { get; set; }

        [JsonProperty("Accepted")]
        public bool Accepted { get; set; }

        [JsonProperty("Warehouse1Id")]
        public Nullable<int> Warehouse1Id { get; set; }

        [JsonProperty("Value")]
        public decimal Value { get; set; }

        [JsonProperty("Rating")]
        public int Rating { get; set; }

        [JsonProperty("InWarehouse")]
        public bool InWarehouse { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Appointment> Appointments { get; set; }
        //public virtual AspNetUser AspNetUser { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Delivery> Deliveries { get; set; }
        //public virtual Field Field { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<PersonProductMark> PersonProductMarks { get; set; }
        //public virtual Product Product { get; set; }
        //public virtual Warehouse1 Warehouse1 { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ReservedProduct> ReservedProducts { get; set; }
    }
}
