//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_PCL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse1()
        {
            this.PersonProducts = new HashSet<PersonProduct>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StoringId { get; set; }
        public bool Status { get; set; }
        public Nullable<int> TownshipId { get; set; }
        public string GeographicPosition_Longitude { get; set; }
        public string GeographicPosition_Latitude { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonProduct> PersonProducts { get; set; }
        public virtual Storing Storing { get; set; }
        public virtual Township Township { get; set; }
    }
}
