//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProductMark
    {
        public int Id { get; set; }
        public int PersonProductId { get; set; }
        public int MarkId { get; set; }
    
        public virtual Mark Mark { get; set; }
        public virtual PersonProduct PersonProduct { get; set; }
    }
}
