//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonProduct()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Deliveries = new HashSet<Delivery>();
            this.PersonProductMarks = new HashSet<PersonProductMark>();
            this.ReservedProducts = new HashSet<ReservedProduct>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime HarvestDate { get; set; }
        public string Neto { get; set; }
        public string Bruto { get; set; }
        public System.DateTime ExparationDate { get; set; }
        public string Quality { get; set; }
        public int FieldId { get; set; }
        public bool Damaged { get; set; }
        public decimal CircaValue { get; set; }
        public bool Urgently { get; set; }
        public bool Status { get; set; }
        public bool Accepted { get; set; }
        public Nullable<int> Warehouse1Id { get; set; }
        public decimal Value { get; set; }
        public int Rating { get; set; }
        public bool InWarehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual Field Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonProductMark> PersonProductMarks { get; set; }
        public virtual Product Product { get; set; }
        public virtual Warehouse1 Warehouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedProduct> ReservedProducts { get; set; }
    }
}
