//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int BuyerRequestId { get; set; }
        public string UserId { get; set; }
        public string Details { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
        public bool Accepted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BuyerRequest BuyerRequest { get; set; }
    }
}
