//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPPHercegovina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMembership
    {
        public int Id { get; set; }
        public int MembershipId { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateOfPayment { get; set; }
        public string PictureUrl { get; set; }
        public bool Approved { get; set; }
        public bool Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Membership Membership { get; set; }
    }
}
